/**:
  ros__parameters:
    # esdf settings
    esdf_slice_height: 0.0
    esdf_2d_min_height: -0.1
    esdf_2d_max_height: 0.3
    # Lidar settings
    use_lidar: false
    # QoS settings
    depth_qos: "SENSOR_DATA"
    color_qos: "SENSOR_DATA"
    map_clearing_frame_id: "camera"
    # Rviz visualization
    slice_visualization_attachment_frame_id: "camera"
    log_level: "debug"
    voxel_size: 0.05

    static_mapper:
      do_depth_preprocessing: true
